version: '2'
services:
  registryservice:
    build: registryservice
    mem_limit: 512M
    ports:
      - "8761:8761"
  configservice:
    build: configservice
    mem_limit: 512M
    ports:
      - "8888:8888"
    environment:
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://172.17.0.1:8761/eureka
  counterservice:
    build: counterservice
    mem_limit: 512M
    ports:
      - "8181:8181"
