version: '2'
services:
  configservice:
    build: configservice
    mem_limit: 512M
    ports:
      - "8888:8888"
  counterservice:
    build: counterservice
    mem_limit: 512M
    ports:
      - "8181:8181"

